#include "gen/hello.h" // Generated by wit-bindgen

void wasi_http_incoming_handler_handle(
    wasi_http_incoming_handler_own_incoming_request_t request,
    wasi_http_incoming_handler_own_response_outparam_t response_outparam
) {
    auto response = wasi_http_types_new_outgoing_response(200, nullptr);
    auto body = wasi_http_types_outgoing_response_write(response);
    
    // In a real app, you'd send your WebGPU-ready data here
    uint8_t msg[] = "Hello from the wasmCloud C++ Actor!";
    wasi_io_streams_write(body, msg, sizeof(msg));
    
    wasi_http_incoming_handler_set_response_outparam(response_outparam, response);
}